version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
#    networks:
#      - springmysql-net
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
#  drone-feeder:
#    image: drone-feeder
#    depends_on:
#      - db
#    networks:
#      - springmysql-net
#    build: .
#    restart: always
#    ports:
#      - "8888:8080"
#    expose:
#      - "8080"

#networks:
#  springmysql-net: